theme: jekyll-theme-minimal
title: Svadba T&M
description: Informácie o svadbe
logo: https://photos.google.com/share/AF1QipOYOYmqDcgBfz2-I_w3kLhPkgiF6OJJJTbaCaC-GCd9t9lFn29BJG8LFM7aKqS4dA/photo/AF1QipOmonaybRNF_AWe31YrYUejFtlycQpOGUiWaHiN?key=T3pnQmV2djVGZ3hyQTY4X05HLUFzSVNISmktSkl3
